operating_system:
  make_command: "wsl -d Ubuntu-20.04 make"
  #ip: "10.0.2.15"
  #gateway_ip: "10.0.2.2"
  #netmask: 24
  ip: "192.168.0.13"
  gateway_ip: "192.168.0.1"
  netmask: 24
vbox:
  vboxmanage_exe_path: "/Program\ Files/Oracle/VirtualBox/VBoxManage.exe"
  name: "CustomOS"
  serial_logfile:
    path: "/Users/jrmam/Desktop/vbox/outfile.txt"
  pcap_file:
    path: "/Users/jrmam/Desktop/vbox/dump.pcap"
  disk:
    path: "/Users/jrmam/Desktop/vbox/CustomOS_11.vdi"
    actual_disk_start: 2097152
qemu:
  qemu_exe_path: "/Program\ Files/qemu/qemu-system-x86_64.exe"
  cmd_params_path: "/Users/jrmam/Desktop/qemu/cmd_params.cfg"
  serial_logfile:
    path: "/Users/jrmam/Desktop/qemu/outfile.txt"
  pcap_file:
    path: "/Users/jrmam/Desktop/qemu/dump.pcap"
  disk:
    path: "/Users/jrmam/Desktop/qemu/image.bin"
required_testing_info:
  mac: "08:00:27:A0:3D:FC"
  #client_ip: "10.0.2.3"
  client_ip: "192.168.0.135"